const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0NNTzBNSWpFaEZBdW9NdTFXRjBOWk5Hem92VVVLb0RxaVhDRHJucVYxaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUVBtbWNrS2hrTUJkZnFCMFduZGZzejlCZDh4N3F4cyt1WHRCZVFZN1F6cz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnRkkxdHZEOVREZ3BCcU5mWU9sQ0xpZ3ZwSGZiYTZwTHFWTWNWQ1BVS0hBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4WXY0T3crQUg4TklhbkE4eS81N08vTEZLQnNnTmxmLy9oc25OMXZXRFdNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJFaGRWSGFsVHN5VmhWZitvaHBneDc2Uk5EVVkzUWlIWE5oZ2ZLQTRFR2M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZuSWU4QnZYYlg3WDNacXk2Y0cyNTVWRU5NRHJEWXdVemp1ZE9rTDY5bFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0tIcEh3aXVRTFRZUU43WW1vZVV0dm9BdEZ1K2pFaW42NWNNa0wxYm1Xcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUlETnAxb1Q2V2tCcERzbW9oZnJQSy9vZ1BvbmZHMDRDRytpd1ppbkdpZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBKWWNMWjNiUXMzZWtiaFBtS0RMOGxIQlJORDlHbU9PZjZKZ1ZrLzRBTkRWbUFMbUxhZTBLT0VJUXdxcFhUR1dYS3NtSXRXZTIvQVgyTURYSk83RkF3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjMsImFkdlNlY3JldEtleSI6ImJKRVh4TGxNOXV2Y3pGUnRmRi8vUWlYdDdUK0JKQlFNNURZR2V1YWFiVEU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjVPQlNLN1BEIiwibWUiOnsiaWQiOiIxODc2MjA3NTc1OTo2QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTAzNzE1NTQxMzUyNjAyOjZAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQQ0N5K1FGRUs3Vmw4NEdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJMY21wYVlNdTlsOFQ3a1dGZlJFY0RZOFJBRWlMZWJ3Y1dxOHV0ci9TTncwPSIsImFjY291bnRTaWduYXR1cmUiOiI5dUEvaVNad0trZUMyY04wSWNmczdORWlCbzl1bnBJS3pjMVBtaFhCcnc1eHRNMy9DalZUT1pvYmtJb2laWDJvbktRT3F1cmQ2emlMNnB1ZStZN3hEUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSkp0Z0ZrczFKWW84ZjBuR0JIU200ZnR4b2JkamQyTjBjanBQK0lFOEhVVVdjT1JCbEpXaTNFS1BNQ2JraFJtZXMzMW5SN2pSbHZmMWQ2dWlVU2JSQ3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIxODc2MjA3NTc1OTo2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlMzSnFXbURMdlpmRSs1RmhYMFJIQTJQRVFCSWkzbThIRnF2THJhLzBqY04ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlBZ2dTIn0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc3NDU3ODM1OCwibGFzdFByb3BIYXNoIjoiM21sMWpTIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFOVjEifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
